[workspace]
members = [
]
[package]
name = "minishell-rs"
authors = ["Jonstep101010"]
version = "0.0.1"
publish = false
edition = "2021"
autobins = false

[[bin]]
path = "src/main.rs"
name = "minishell-rs"
[lib]
path = "src/lib.rs"
name = "msh"
[dependencies]
gnu-readline-sys = "0.1.0"
rustyline = "14.0.0"
