
#include "ft_strlen.c"
#include "ft_memset.c"
#include "ft_calloc.c"
#include "ft_strjoin.c"
#include "ft_substr.c"
#include "ft_itoa.c"
#include "ft_isalnum.c"
#include "ft_strdup.c"
#include "ft_memmove.c"
#include "ft_bzero.c"
#include "ft_memcpy.c"
#include "ft_isalpha.c"
#include "ft_isdigit.c"
#include "ft_isprint.c"
#include "ft_isascii.c"
#include "ft_strtrim.c"
#include "ft_strchr.c"
#include "ft_strrchr.c"
#include "ft_strlcpy.c"
#include "ft_strlcat.c"
#include "ft_strncmp.c"
#include "ft_strnstr.c"

#include "str_cchr.c"
#include "arr_len.c"
#include "arr_free.c"
#include "arr_dup.c"

#include "support_printf.c"
#include "print_arr.c"


